name: Create ElasticSearch
description: Creates Elastic search on a cluster
inputs:
  ELASTIC_URL:
    description: Elastic URL to create
    required: true
  ELASTIC_PORT:
    description: Elastic port to create elastic at
    required: true
  ELASTIC_USER:
    description: Elastic user to login using
    required: true
  ELASTIC_PASSWORD:
    description: Elastic password to login using
    required: true

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Install Helm & add repos
      shell: bash
      run: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
        helm repo add stable https://charts.helm.sh/stable
        helm repo update
    - name: Deploy Elasticsearch
      shell: bash
      env:
        ELASTIC_URL: ${{ inputs.ELASTIC_URL }}
        ELASTIC_PORT: ${{ inputs.ELASTIC_PORT }}
        ELASTIC_USER: ${{ inputs.ELASTIC_USER }}
        ELASTIC_PASSWORD: ${{ inputs.ELASTIC_PASSWORD }}
      run: |
        echo "ELASTIC_URL: ${ELASTIC_URL}"
        echo "ELASTIC_PORT: ${ELASTIC_PORT}"
        echo "ELASTIC_USER: ${ELASTIC_USER}"
        echo "ELASTIC_PASSWORD:${ELASTIC_PASSWORD}"
        
        
        # nodePort mapping 32766 -> http://localhost:9091
        helm install \
        --wait --timeout 360s \
        elasticsearch \
        oci://registry-1.docker.io/bitnamicharts/elasticsearch \
        --set master.masterOnly=false \
        --set master.replicaCount=1 \
        --set data.replicaCount=0 \
        --set coordinating.replicaCount=0 \
        --set ingest.replicaCount=0 \
        --set service.type=NodePort \
        --set service.nodePorts.restAPI=32766 \
        --set security.elasticPassword=test \
        --set security.enabled=true \
        --set image.tag=7.17.23-debian-12-r0 \
        --set security.tls.autoGenerated=true