name: Create ElasticSearch
description: Creates Elastic search on a cluster
inputs:
  ELASTIC_PORT:
    description: Elastic port to create elastic at
    required: true
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Install Helm & add repos
      shell: bash
      run: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
        helm repo add elastic https://helm.elastic.co
        helm repo update
    - name: Deploy Elasticsearch
      shell: bash
      env:
        ELASTIC_PORT: ${{ inputs.ELASTIC_PORT }}
      run: |
        # nodePort mapping 32766 -> http://localhost:9091
        helm install \
        --wait --timeout 720s \
        elasticsearch \
        elastic/elasticsearch \
        --set security.enabled=true \
        --set service.type=NodePort \
        --set service.nodePort=32766

        export ELASTIC_PASSWORD="$(kubectl get secret elasticsearch-master-credentials -o jsonpath='{.data.password}' | base64 --decode)"
        echo "ELASTIC PASSWORD: $ELASTIC_PASSWORD"
        echo $ELASTIC_PASSWORD > elastic_password.txt

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: elastic_password.txt
