name: Rebuild krkn-hub
description: Rebuilds krkn-hub images
inputs:
  QUAY_USER:
    description: Quay user
    required: true
  QUAY_TOKEN:
    description: Quay token
    required: true
  AUTOPUSH:
    description: Auto push token
    required: true

runs:
  using: composite
  steps:
    - name: Checkout krkn-hub repo
      uses: actions/checkout@v3
      with:
        repository: krkn-chaos/krkn-hub
        path: krkn-hub
    - name: Login in quay
      shell: bash
      run: docker login quay.io -u ${QUAY_USER} -p ${QUAY_TOKEN}
      env:
        QUAY_USER: ${{ inputs.QUAY_USER }}
        QUAY_TOKEN: ${{ inputs.QUAY_TOKEN }
    - name: Add krknctl metadata to Dockerfiles
      run: |
        bash build.sh
    - name: Build the Docker images
      shell: bash
      run: docker compose build --parallel
      working-directory: ./krkn-hub
    - name: Push the Docker images
      shell: bash
      run: docker compose push
      working-directory: ./krkn-hub
    - name: Make push to Prow-Scripts
      uses: redhat-chaos/actions/prow-scripts@main
      with:
        AUTOPUSH: ${{ inputs.AUTOPUSH }}
