name: Auto Push 
on:
  workflow_dispatch:
    inputs:
      test_list:
        description: Only run tests that match the regular expression
        default: ""
        required: false

runs:
  using: composite
  steps:
  - name: Check out code
    uses: actions/checkout@main
    with:
      repository: redhat-chaos/prow-scripts
      path: prow-scripts
  - name: Update README with current date/time
    shell: bash
    working-directory: ./prow-scripts
    run: |
      current_date=$(date +"%H:%M %b %d %Y")
      sed -i "s/[0-9]\{2\}:[0-9]\{2\} [A-Z][a-z]\{2\} [0-9]\{2\} [0-9]\{4\}/$current_date/g" README.md
      git config --global user.name 'Paige Auto User'
      git config --global user.email 'prubenda@redhat.com'
      git add README.md
      git commit -am "Automated readme update"
      git push