name: Auto Push 
on:
  workflow_dispatch:
    inputs:
      test_list:
        description: Only run tests that match the regular expression
        default: ""
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@main
    - name: Update README with current date/time
      run: |
        current_date=$(date +"%H:%M %b %d %Y")
        sed -i "s/[0-9]\{2\}:[0-9]\{2\} [A-Z][a-z]\{2\} [0-9]\{2\} [0-9]\{4\}/$current_date/g" README.md
        git config --global user.name 'Auto User'
        git config --global user.email 'auto@users.noreply.github.com'
        git add README.md
        git commit -am "Automated readme update"
        git push