on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:

jobs:
  test_action:
    runs-on: ubuntu-latest
    name: Test KinD action
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Kind Action Test
        uses: ./kind
      - name: Get Nodes
        run: kubectl get nodes
      - name: Create POD
        run: kubectl apply -f https://k8s.io/examples/pods/simple-pod.yaml
      - name: Prometheus Action Test
        uses: ./prometheus
      - name: Elastic Action Test
        uses: ./elastic
      - name: Check pods
        run: kubectl get pods -A
